name: Deploy to GitHub Pages

on:
  workflow_dispatch: # Only run manually
  # push:
  #   branches:
  #     - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: false # Temporarily disable this workflow
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Clean build cache
        run: npm run clean

      - name: Build
        run: npm run build

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}
          clean: true
          single-commit: true
